compatibility_date = "2024-01-01"

# database_name can be anything you want
# you target it by that name with wrangler
# for example
#
# wrangler d1 execute D1_DB --local --file .\schema-migration.sql
#	

[[d1_databases]]
binding = "DB"                                       # Should match preview_database_id
database_name = "D1_DB"
database_id = "the-id-of-your-D1-database-goes-here" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB"                           # Required for Pages local development
