name="youtube-demo"
compatibility_date = "2024-01-01"

# database_name can be anything you want
# you target it by that name with wrangler
# for example
#
# wrangler d1 execute D1_DB --local --file .\schema-migration.sql
#	

pages_build_output_dir = "./.svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"                                       # Should match preview_database_id
database_name = "todo"
database_id = "91645e0b-bc49-43d3-81f3-cbab44dad067" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB"                           # Required for Pages local development
